# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analysis_pb2 as analysis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatistics = channel.unary_unary(
                '/analysis.Analyzer/GetStatistics',
                request_serializer=analysis__pb2.StatisticsRequest.SerializeToString,
                response_deserializer=analysis__pb2.StatisticsResponse.FromString,
                _registered_method=True)
        self.DetectAnomalies = channel.unary_unary(
                '/analysis.Analyzer/DetectAnomalies',
                request_serializer=analysis__pb2.AnomalyRequest.SerializeToString,
                response_deserializer=analysis__pb2.AnomalyResponse.FromString,
                _registered_method=True)
        self.PredictHealthRisk = channel.unary_unary(
                '/analysis.Analyzer/PredictHealthRisk',
                request_serializer=analysis__pb2.HealthRiskRequest.SerializeToString,
                response_deserializer=analysis__pb2.HealthRiskResponse.FromString,
                _registered_method=True)


class AnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectAnomalies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictHealthRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatistics,
                    request_deserializer=analysis__pb2.StatisticsRequest.FromString,
                    response_serializer=analysis__pb2.StatisticsResponse.SerializeToString,
            ),
            'DetectAnomalies': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAnomalies,
                    request_deserializer=analysis__pb2.AnomalyRequest.FromString,
                    response_serializer=analysis__pb2.AnomalyResponse.SerializeToString,
            ),
            'PredictHealthRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictHealthRisk,
                    request_deserializer=analysis__pb2.HealthRiskRequest.FromString,
                    response_serializer=analysis__pb2.HealthRiskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analysis.Analyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analysis.Analyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Analyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.Analyzer/GetStatistics',
            analysis__pb2.StatisticsRequest.SerializeToString,
            analysis__pb2.StatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.Analyzer/DetectAnomalies',
            analysis__pb2.AnomalyRequest.SerializeToString,
            analysis__pb2.AnomalyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictHealthRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.Analyzer/PredictHealthRisk',
            analysis__pb2.HealthRiskRequest.SerializeToString,
            analysis__pb2.HealthRiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
