// <auto-generated />
namespace Servidor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class First_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202605291120263_First_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
