// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: analysis.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AnalysisService {
  public static partial class Analyzer
  {
    static readonly string __ServiceName = "analysis.Analyzer";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AnalysisService.StatisticsRequest> __Marshaller_analysis_StatisticsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AnalysisService.StatisticsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AnalysisService.StatisticsResponse> __Marshaller_analysis_StatisticsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AnalysisService.StatisticsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AnalysisService.AnomalyRequest> __Marshaller_analysis_AnomalyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AnalysisService.AnomalyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AnalysisService.AnomalyResponse> __Marshaller_analysis_AnomalyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AnalysisService.AnomalyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AnalysisService.HealthRiskRequest> __Marshaller_analysis_HealthRiskRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AnalysisService.HealthRiskRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AnalysisService.HealthRiskResponse> __Marshaller_analysis_HealthRiskResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AnalysisService.HealthRiskResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::AnalysisService.StatisticsRequest, global::AnalysisService.StatisticsResponse> __Method_GetStatistics = new grpc::Method<global::AnalysisService.StatisticsRequest, global::AnalysisService.StatisticsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetStatistics",
        __Marshaller_analysis_StatisticsRequest,
        __Marshaller_analysis_StatisticsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::AnalysisService.AnomalyRequest, global::AnalysisService.AnomalyResponse> __Method_DetectAnomalies = new grpc::Method<global::AnalysisService.AnomalyRequest, global::AnalysisService.AnomalyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DetectAnomalies",
        __Marshaller_analysis_AnomalyRequest,
        __Marshaller_analysis_AnomalyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::AnalysisService.HealthRiskRequest, global::AnalysisService.HealthRiskResponse> __Method_PredictHealthRisk = new grpc::Method<global::AnalysisService.HealthRiskRequest, global::AnalysisService.HealthRiskResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PredictHealthRisk",
        __Marshaller_analysis_HealthRiskRequest,
        __Marshaller_analysis_HealthRiskResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AnalysisService.AnalysisReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Analyzer</summary>
    [grpc::BindServiceMethod(typeof(Analyzer), "BindService")]
    public abstract partial class AnalyzerBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::AnalysisService.StatisticsResponse> GetStatistics(global::AnalysisService.StatisticsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::AnalysisService.AnomalyResponse> DetectAnomalies(global::AnalysisService.AnomalyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::AnalysisService.HealthRiskResponse> PredictHealthRisk(global::AnalysisService.HealthRiskRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Analyzer</summary>
    public partial class AnalyzerClient : grpc::ClientBase<AnalyzerClient>
    {
      /// <summary>Creates a new client for Analyzer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AnalyzerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Analyzer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AnalyzerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AnalyzerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AnalyzerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::AnalysisService.StatisticsResponse GetStatistics(global::AnalysisService.StatisticsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStatistics(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::AnalysisService.StatisticsResponse GetStatistics(global::AnalysisService.StatisticsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStatistics, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::AnalysisService.StatisticsResponse> GetStatisticsAsync(global::AnalysisService.StatisticsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStatisticsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::AnalysisService.StatisticsResponse> GetStatisticsAsync(global::AnalysisService.StatisticsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStatistics, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::AnalysisService.AnomalyResponse DetectAnomalies(global::AnalysisService.AnomalyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DetectAnomalies(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::AnalysisService.AnomalyResponse DetectAnomalies(global::AnalysisService.AnomalyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DetectAnomalies, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::AnalysisService.AnomalyResponse> DetectAnomaliesAsync(global::AnalysisService.AnomalyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DetectAnomaliesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::AnalysisService.AnomalyResponse> DetectAnomaliesAsync(global::AnalysisService.AnomalyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DetectAnomalies, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::AnalysisService.HealthRiskResponse PredictHealthRisk(global::AnalysisService.HealthRiskRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PredictHealthRisk(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::AnalysisService.HealthRiskResponse PredictHealthRisk(global::AnalysisService.HealthRiskRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PredictHealthRisk, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::AnalysisService.HealthRiskResponse> PredictHealthRiskAsync(global::AnalysisService.HealthRiskRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PredictHealthRiskAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::AnalysisService.HealthRiskResponse> PredictHealthRiskAsync(global::AnalysisService.HealthRiskRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PredictHealthRisk, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AnalyzerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AnalyzerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AnalyzerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetStatistics, serviceImpl.GetStatistics)
          .AddMethod(__Method_DetectAnomalies, serviceImpl.DetectAnomalies)
          .AddMethod(__Method_PredictHealthRisk, serviceImpl.PredictHealthRisk).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AnalyzerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetStatistics, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AnalysisService.StatisticsRequest, global::AnalysisService.StatisticsResponse>(serviceImpl.GetStatistics));
      serviceBinder.AddMethod(__Method_DetectAnomalies, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AnalysisService.AnomalyRequest, global::AnalysisService.AnomalyResponse>(serviceImpl.DetectAnomalies));
      serviceBinder.AddMethod(__Method_PredictHealthRisk, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AnalysisService.HealthRiskRequest, global::AnalysisService.HealthRiskResponse>(serviceImpl.PredictHealthRisk));
    }

  }
}
#endregion
