# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preprocess.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'preprocess.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10preprocess.proto\x12\rpreprocessing\"]\n\nSensorData\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x0c\n\x04zone\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\t\"]\n\rProcessedData\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x18\n\x10normalized_value\x18\x02 \x01(\t\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2^\n\x14PreProcessingService\x12\x46\n\x0bProcessData\x12\x19.preprocessing.SensorData\x1a\x1c.preprocessing.ProcessedDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preprocess_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=35
  _globals['_SENSORDATA']._serialized_end=128
  _globals['_PROCESSEDDATA']._serialized_start=130
  _globals['_PROCESSEDDATA']._serialized_end=223
  _globals['_PREPROCESSINGSERVICE']._serialized_start=225
  _globals['_PREPROCESSINGSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
